name: Build Android Plugin AARs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up JDK 17
        uses: actions/setup-java@v6
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AARs
        run: ./gradlew assemble

      - name: Package AndroidIAPP plugin
        run: |
          mkdir -p android_IAPP
          cp AndroidIAPP/build/outputs/aar/AndroidIAPP-release.aar android_IAPP/
          cp AndroidIAPP/build/outputs/aar/AndroidIAPP-debug.aar android_IAPP/
          cp addon/android_IAPP/AndroidIAPP.gd android_IAPP/
          cp addon/android_IAPP/GooglePlayBilling.gd android_IAPP/
          cp addon/android_IAPP/plugin.cfg android_IAPP/
          zip -r android_IAPP.zip android_IAPP

      - name: Upload AndroidIAPP plugin
        uses: actions/upload-artifact@v7
        with:
          name: android_IAPP
          path: android_IAPP.zip
